[package]
name = "wei-updater"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wei-run = "0.1.9"
wei-env = "0.2.4"
serde_yaml = "0.9"
tokio = { version = "1.28", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
single-instance = "0.3"