[package]
name = "wei-updater"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wei-run = "0.1.9"
wei-env = "0.2.10"
wei-log = "0.2.3"
wei-daemon = "0.2.5"
serde_yaml = "0.9"
serde_json = "1"
tokio = { version = "1.28", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
single-instance = "0.3"
winrt-notification = "0.5.1"